version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /cicd/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /cicd/docker-credentials/password
    DOCKER_REGISTRY_URL: /cicd/docker-registry/url
    SONAR_TOKEN: /cicd/sonar/sonar-token

phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto17
    commands:
      - echo "Installing SonarQube Scanner..."
      - export SONAR_SCANNER_VERSION=4.7.0.2747
      - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
      - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
      - export PATH=$SONAR_SCANNER_HOME/bin:$PATH
      - sonar-scanner --version

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - echo "Starting SonarQube analysis..."

  build:
    commands:
      - echo "Running tests..."
      - echo "Running SonarQube analysis..."
      - cd Swiggy_clone
      - sonar-scanner -Dsonar.projectKey=swiggy -Dsonar.sources=. -Dsonar.host.url=http://16.4.52.101:9000 -Dsonar.token=$SONAR_TOKEN

  post_build:
    commands:
      - echo "SonarQube analysis completed."
      - echo "Sending CodeBuild status email..."
      - aws ses send-email --from "nehru.k1411@gmail.com" --to "nehru.k1411@gmail.com" --subject "CodeBuild Status" --text "CodeBuild completed with status $CODEBUILD_BUILD_STATUS" --region "ap-south-1"

artifacts:
  files:
    - Swiggy_clone/appspec.yaml
